#!/usr/bin/env ruby

$: . unshift(File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib')))
require 'bert'
require 'growlamqp'

GrowlAMQP.monitor!(:host => "example.org") do | msg |
  msg
end
